######################################################################
# Automatically generated by qmake (3.0) Sat Jul 30 00:15:10 2016
######################################################################

TEMPLATE = app
TARGET = webcam-pov-server
INCLUDEPATH += .
QT += multimediawidgets

# Input
SOURCES += main.cpp CameraFrameGrabber.cpp Server.cpp
HEADERS += CameraFrameGrabber.h Server.h
